[package]
name = "chumsky"
version = "0.6.0"
description = "A friendly parser combinator crate"
authors = ["Joshua Barretto <joshua.s.barretto@gmail.com>"]
repository = "https://github.com/zesterer/chumsky"
license = "MIT"
keywords = ["parser", "combinator", "token", "language", "syntax"]
categories = ["parsing", "text-processing"]
edition = "2018"
exclude = [
    "/misc/*",
	"/benches/*",
]

[features]
default = ["ahash"]

[dependencies]
# Use `ahash` for maintaining sets of expected inputs
ahash = { version = "^0.3", optional = true }

[dev-dependencies]
ariadne = "0.1.2"
pom = "3.0"
